name: Angular Build
on:
  push:
    branches: [ main, master ] # Triggers on pushes to main or master branch
  pull_request:
    branches: [ main, master ] # Triggers on pull requests to main or master branch

jobs:
  build:
    name: Build Angular App on ${{ matrix.os }} with Node ${{ matrix.node-version }}
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: ['16.14.x', '18.19.1', '22.14.x']

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        # Checks out your repository under $GITHUB_WORKSPACE, so your job can access it

      - name: Setup Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: 'npm' # Enables caching for npm dependencies

      - name: Install Dependencies
        run: npm install

      - name: Build Angular Application
        run: npm run build

      - name: Lint Code
        run: npm run lint

      - name: Run Tests
        run: npm run test

      #Upload build artifact
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: angular-app-dist-${{ matrix.os }}-${{ matrix.node-version }} # Name of the artifact, now includes OS and Node version
          path: docs/
          if-no-files-found: error
